### ISSUE TITLE
[chore] 프로젝트 세팅

### ISSUE THREAD

**Issue by gyu85** [f-lab-edu/time-tracker#1]
# 작업 내용
- 기본 폴더 구조 세팅
- reset style setting

- node version: 20.18.0
- vite: 5.4.8

**Comment by f-lab-guell** [comment]
vite 고르신 이유가 따로 있으신가요?

**Comment by gyu85** [comment]
> vite 고르신 이유가 따로 있으신가요?

안녕하세요?
답변이 늦었습니다. ;;

고민한 부분은 성능에서 오는 장점 보다는(문서를 봐도.. 잘 모르는 부분이 많아서;;)
공식문서에서 봤을 때 빠르게 세팅하고 설정하기 편한 부분 때문에 Vite를 선택했습니다.
